# Generated by Django 4.2.3 on 2023-08-20 05:13

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChainOfCustody',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('COC_UUID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Client_ID', models.CharField(max_length=60, verbose_name='Client ID')),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Order_of_the_Form', models.PositiveIntegerField(verbose_name='Order of the Form cronology')),
                ('COC_File_Upload', models.FileField(upload_to='COC Files/%d/%m/%Y/', verbose_name='COC File Upload')),
                ('COC_ID', models.CharField(max_length=1000, verbose_name='COC Form ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Chain of Custody (FO-063)',
            },
        ),
        migrations.CreateModel(
            name='SampleIntakeForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SIF_UUID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Sample_ID', models.CharField(max_length=40)),
                ('Sample_Name', models.CharField(max_length=300, verbose_name='Sample Name')),
                ('Matrix', models.CharField(max_length=300, verbose_name='Matrix')),
                ('Batch_Number', models.CharField(max_length=300, verbose_name='Batch Number')),
                ('Sample_Size', models.PositiveIntegerField(verbose_name='Sample Size')),
                ('Batch_Size', models.PositiveIntegerField(verbose_name='Batch Size')),
                ('Distributor_Micro_business_Name', models.CharField(max_length=300, verbose_name='Distributor / Micro business Name')),
                ('Distributor_Micro_business_License_No', models.CharField(max_length=300, verbose_name='Distributor / Micro business License No')),
                ('Chain_of_Custody_Number', models.CharField(max_length=300, verbose_name='Chain of Custody Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sample Intake Log (FO-043)',
            },
        ),
        migrations.CreateModel(
            name='SampleRetainForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SRF_UUID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Sample_ID', models.CharField(editable=False, max_length=40)),
                ('Sample_Name', models.CharField(max_length=300, verbose_name='Sample Name')),
                ('Matrix', models.CharField(max_length=300, verbose_name='Matrix')),
                ('Batch_Number', models.CharField(max_length=300, verbose_name='Batch Number')),
                ('Sample_Size', models.PositiveIntegerField(verbose_name='Sample Size')),
                ('Batch_Size', models.PositiveIntegerField(verbose_name='Batch Size')),
                ('Distributor_Micro_business_Name', models.CharField(max_length=300, verbose_name='Distributor / Micro business Name')),
                ('Distributor_Micro_business_License_No', models.CharField(max_length=300, verbose_name='Distributor / Micro business License No')),
                ('Chain_of_Custody_Number', models.CharField(max_length=300, verbose_name='Chain of Custody Number')),
                ('Days_Retailed', models.PositiveIntegerField(verbose_name='Days Retailed')),
                ('Disposal_Status', models.CharField(max_length=300, verbose_name='Disposal Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sample Sample Retention Log (FO-044)',
            },
        ),
        migrations.CreateModel(
            name='SampleTrackingForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('STF_UUID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Sample_ID', models.CharField(max_length=40)),
                ('SIF_Id', models.CharField(editable=False, max_length=40)),
                ('Cannabinoids', models.BooleanField(default=False, verbose_name='Cannabinoids')),
                ('Cannabinoids_Workgroup_ID', models.CharField(max_length=300, verbose_name='Cannabinoids Workgroup ID')),
                ('Cannabinoids_Sample_weight', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True, verbose_name='Cannabinoids Sample weight')),
                ('Cannabinoids_Analysis_Status', models.CharField(choices=[('Null', 'NA'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='NA', max_length=100)),
                ('Water_Activity', models.BooleanField(default=False, verbose_name='Water Activity')),
                ('Water_Activity_Workgroup_ID', models.CharField(max_length=300, verbose_name='Water Activity Workgroup ID')),
                ('Water_Activity_Sample_weight', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True, verbose_name='Water Activity Sample weight')),
                ('Water_Activity_Analysis_Status', models.CharField(choices=[('Null', 'NA'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='NA', max_length=100)),
                ('Micro', models.BooleanField(default=False, verbose_name='Micro')),
                ('Micro_Workgroup_ID', models.CharField(max_length=300, verbose_name='Micro Workgroup ID')),
                ('Micro_Sample_weight', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True, verbose_name='Micro Sample weight')),
                ('Micro_Analysis_Status', models.CharField(choices=[('Null', 'NA'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='NA', max_length=100)),
                ('Pesticides_and_Mycotoxins', models.BooleanField(default=False, verbose_name='Pesticides and Mycotoxins')),
                ('Pesticides_and_Mycotoxins_Workgroup_ID', models.CharField(max_length=300, verbose_name='Pesticides and Mycotoxins Workgroup ID')),
                ('Pesticides_and_Mycotoxins_Sample_weight', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True, verbose_name='Pesticides and Mycotoxins Sample weight')),
                ('Pesticides_and_Mycotoxins_Analysis_Status', models.CharField(choices=[('Null', 'NA'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='NA', max_length=100)),
                ('Residual_Solvents', models.BooleanField(default=False, verbose_name='Residual Solvents')),
                ('Residual_Solvents_Workgroup_ID', models.CharField(max_length=300, verbose_name='Residual Solvents Workgroup ID')),
                ('Residual_Solvents_Sample_weight', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True, verbose_name='Residual Solvents Sample weight')),
                ('Residual_Solvents_Analysis_Status', models.CharField(choices=[('Null', 'NA'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='NA', max_length=100)),
                ('Foreign_Material', models.BooleanField(default=False, verbose_name='Foreign Material')),
                ('Foreign_Material_Workgroup_ID', models.CharField(max_length=300, verbose_name='Foreign Material Workgroup ID')),
                ('Foreign_Material_Sample_weight', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True, verbose_name='Foreign Material Sample weight')),
                ('Foreign_Material_Analysis_Status', models.CharField(choices=[('Null', 'NA'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='NA', max_length=100)),
                ('Moisture_Content', models.BooleanField(default=False, verbose_name='Moisture Content')),
                ('Moisture_Content_Workgroup_ID', models.CharField(max_length=300, verbose_name='Moisture Content Workgroup ID')),
                ('Moisture_Content_Sample_weight', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True, verbose_name='Moisture Content Sample weight')),
                ('Moisture_Content_Analysis_Status', models.CharField(choices=[('Null', 'NA'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='NA', max_length=100)),
                ('Heavy_Metals', models.BooleanField(default=False, verbose_name='Heavy Metals')),
                ('Heavy_Metals_Workgroup_ID', models.CharField(max_length=300, verbose_name='Heavy Metals Workgroup ID')),
                ('Heavy_Metals_Sample_weight', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=30, null=True, verbose_name='Heavy Metals Sample weight')),
                ('Heavy_Metals_Analysis_Status', models.CharField(choices=[('Null', 'NA'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='NA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sample Intake Log (FO-114)',
            },
        ),
    ]
