# Generated by Django 4.2.3 on 2023-08-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainofcustody',
            options={},
        ),
    ]
