# Generated by Django 4.2.3 on 2023-08-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_chainofcustody_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainofcustody',
            options={'verbose_name_plural': 'Chain of Custody (FO-063)'},
        ),
    ]
