# Generated by Django 4.2.3 on 2023-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_chainofcustody_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainofcustody',
            name='Date',
            field=models.DateField(default=False, verbose_name='Date'),
        ),
    ]
