# Generated by Django 4.2.3 on 2023-08-20 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_chainofcustody_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainofcustody',
            name='Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
