# Generated by Django 4.2.3 on 2023-08-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_chainofcustody_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainofcustody',
            name='COC_File_Upload',
            field=models.FileField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
