# Generated by Django 4.2.3 on 2023-08-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_chainofcustody_coc_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainofcustody',
            name='COC_File_Upload',
            field=models.FileField(upload_to=''),
        ),
    ]
