# Generated by Django 4.2.3 on 2023-08-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_chainofcustody_coc_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainofcustody',
            name='COC_File_Upload',
            field=models.FileField(upload_to='COC Files/%d/%m/%Y/', verbose_name='COC File Upload'),
        ),
    ]
